planner:
  p_goal_x: 15
  p_goal_y: 0
  p_goal_z: 0
  planning_time_step: 0.05
  trajectory_piece_max_size: 8
  risk_threshold_replan: 1.0
  replan_time_threshold: 1.2 # make sure > 1.0 because planner replans every seconds
  max_vel: 3.0
  max_acc: 5.0
  max_differentiated_current_a: 3.0

fsm:
  goal_tolerance: 2.5
  replan_tolerance: 1.0

search:
  max_tau: 0.6
  init_max_tau: 0.8
  max_vel: 2
  max_acc: 2
  w_time: 10.0
  horizon: 5.0
  lambda_heu: 5.0
  resolution_astar: 1
  time_resolution: 0.2
  margin: 0.2
  allocate_num: 100000
  check_num: 5

corridor:
  risk_threshold_single_voxel: 0.15
  risk_threshold_corridor: 3.0

optimizer:
  pos_factor: 0.0
  vel_factor: 0.0
  acc_factor: 0.0
  jerk_factor: 0.0
  snap_factor: 1.0  # minimum snap
  delta_corridor: 0.4

  max_vel_optimization: 3 # Constraint in optimization. A little larger than max_vel
  max_acc_optimization: 5 # Constraint in optimization. A little larger than max_acc

map:
  voxel_size_x: 65
  voxel_size_y: 65
  voxel_size_z: 35

  resolution: 0.15
  angle_resolution: 3
  time_resolution: 0.2
  n_risk_map: 3
  n_prediction_per_risk: 3
  n_particles_max_per_voxel: 18
  stddev_pos: 0.05
  stddev_vel: 0.05
  sigma_update: 0.1
  sigma_observation: 0.05
  sigma_localization: 0.00
  newborn/particles_weight: 0.0001
  newborn/particles_number: 20
  newborn/objects_weight: 0.04
  half_fov_horizontal: 48
  half_fov_vertical: 36

  local_update_range_x: 5.5
  local_update_range_y: 5.5
  local_update_range_z: 4.5
  obstacles_inflation: 0.3
  local_map_margin: 10
  ground_height: -0.01

  virtual_ceil_height: 2.9
  visualization_truncate_height: 1.8
  show_occ_time: false
  pose_type: 1
  frame_id: world

visualization:
  rviz_map_center_locked: false
